image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - ms-python.isort
    - ms-python.python
    - charliemarsh.ruff

tasks:
  - name: Local terminal
    command: bash
  - name: Remote Jetson Shell
    command: doppler setup --no-interactive && bash