image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - ms-python.isort
    - ms-python.python
    - charliemarsh.ruff

tasks:
  - name: Local terminal
    command: bash
  - name: tailscaled
    command: sudo tailscaled
  - name: Remote Jetson Shell
    command: sudo -E tailscale up --authkey=$TAILSCALE_AUTHKEY